"use client";

import { ArrowDown, ArrowLeft, ArrowUp, ExternalLink, FilePlus2, Plus, RefreshCw, Trash2, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { GoogleFormsAccess } from "@/lib/googleForms/access";
import type { GoogleFormTemplate } from "@/lib/googleForms/templates";
import type { GoogleFormQuestion, GoogleFormRegistryRow, GoogleQuestionType } from "@/lib/googleForms/types";

type Props = { initialAccess: GoogleFormsAccess; templates: GoogleFormTemplate[] };
type ListResponse = { access: GoogleFormsAccess; connection: { connected: boolean; accountEmail: string }; forms: GoogleFormRegistryRow[]; error?: string };
type MirrorResponse = { responses: Array<{ id: string; submitted_at: string; respondent_email: string | null; answers_json: Record<string, string[]> }>; error?: string };
const questionTypes: Array<[GoogleQuestionType, string]> = [["short_answer", "Short answer"], ["paragraph", "Paragraph"], ["multiple_choice", "Multiple choice"], ["checkbox", "Checkbox"], ["dropdown", "Dropdown"], ["date", "Date"], ["time", "Time"]];
const blankQuestion = (): GoogleFormQuestion => ({ id: crypto.randomUUID(), title: "", type: "short_answer", required: false, options: [] });

export function GoogleFormsManager({ initialAccess, templates }: Props) {
  const [data, setData] = useState<ListResponse>({ access: initialAccess, connection: { connected: false, accountEmail: "" }, forms: [] });
  const [clubKey, setClubKey] = useState(initialAccess.manageableClubs[0]);
  const [templateId, setTemplateId] = useState(templates[0].id);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [activityId, setActivityId] = useState("");
  const [activityTitle, setActivityTitle] = useState(""); const [activityDate, setActivityDate] = useState(""); const [location, setLocation] = useState("");
  const [deadline, setDeadline] = useState(""); const [questions, setQuestions] = useState<GoogleFormQuestion[]>([]);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [selected, setSelected] = useState<string | null>(null); const [mirror, setMirror] = useState<MirrorResponse | null>(null);
  const forms = useMemo(() => data.forms.filter((form) => form.club_key === clubKey), [clubKey, data.forms]);
  async function load() { const response = await fetch("/api/google-forms/forms", { cache: "no-store" }); const next = await response.json() as ListResponse; if (!response.ok) throw new Error(next.error || "Google Forms could not load."); setData(next); }
  useEffect(() => { void load().catch((error) => setMessage((error as Error).message)); }, []);
  function applyTemplate(id: string) { setTemplateId(id); const template = templates.find((item) => item.id === id)!; setQuestions(template.questions.map((question) => ({ ...question, id: crypto.randomUUID(), options: [...question.options] }))); if (!description) setDescription(template.description); }
  function updateQuestion(id: string, patch: Partial<GoogleFormQuestion>) { setQuestions((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item)); }
  function moveQuestion(index: number, offset: -1 | 1) { setQuestions((current) => { const target = index + offset; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  async function create() {
    if (busy) return; setBusy(true); setMessage("");
    try { const response = await fetch("/api/google-forms/forms", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ clubKey, templateId, title, description, activityId, activityTitle, activityDate: activityDate ? new Date(activityDate).toISOString() : "", location, applicationDeadline: deadline ? new Date(deadline).toISOString() : "", questions }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Google Form creation failed."); setTitle(""); setDescription(""); setActivityId(""); setActivityTitle(""); setQuestions([]); setMessage("Google Form created. Google Forms is the application source of truth."); await load(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Google Forms 연결에 문제가 있습니다."); } finally { setBusy(false); }
  }
  async function status(form: GoogleFormRegistryRow, next: "open" | "closed" | "archived") { setBusy(true); try { const response = await fetch(`/api/google-forms/forms/${form.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: next }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Status update failed."); await load(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  async function responses(form: GoogleFormRegistryRow, sync = false) { setSelected(form.id); setBusy(true); try { if (sync) { const syncResponse = await fetch(`/api/google-forms/forms/${form.id}/responses`, { method: "POST" }); const result = await syncResponse.json() as { error?: string }; if (!syncResponse.ok) throw new Error(result.error || "Sync failed."); await load(); } const response = await fetch(`/api/google-forms/forms/${form.id}/responses`, { cache: "no-store" }); const next = await response.json() as MirrorResponse; if (!response.ok) throw new Error(next.error || "Responses could not load."); setMirror(next); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  return <section className="bg-paper py-10 sm:py-16"><div className="mx-auto max-w-7xl px-5 md:px-8">
    <Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold underline"><ArrowLeft className="h-4 w-4" />K_LINE</Link>
    <div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase text-brass">Google Forms</p><h1 className="mt-2 font-serif text-4xl font-semibold text-ink sm:text-5xl">Application management</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-ink/65">New submissions are created only in Google Forms. K_LINE displays a read-only response mirror.</p></div>{initialAccess.canConnect ? <a href="/api/google-forms/oauth/start" className="inline-flex min-h-11 items-center bg-ink px-5 text-sm font-semibold text-paper">{data.connection.connected ? `Reconnect ${data.connection.accountEmail}` : "Connect operations Google account"}</a> : null}</div>
    {message ? <p role="status" className="mt-5 border border-brass/30 bg-brass/10 p-3 text-sm font-semibold text-ink">{message}</p> : null}
    <div className="mt-8 flex gap-2 overflow-x-auto">{initialAccess.manageableClubs.map((club) => <button key={club} onClick={() => setClubKey(club)} className={`min-h-10 whitespace-nowrap px-4 text-sm font-semibold ${clubKey === club ? "bg-navy text-paper" : "border border-ink/15"}`}>{club}</button>)}</div>
    {!initialAccess.isReadOnly ? <div className="mt-6 border border-ink/12 bg-white/55 p-5 sm:p-6"><h2 className="flex items-center gap-2 font-serif text-3xl font-semibold"><FilePlus2 className="h-6 w-6" />Create Google Form</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      <Field label="Template"><select value={templateId} onChange={(event) => applyTemplate(event.target.value)} className="form-field">{templates.map((template) => <option key={template.id} value={template.id}>{template.label}</option>)}</select></Field>
      <Field label="Form title"><input className="form-field" value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="Activity ID"><input className="form-field" value={activityId} onChange={(e) => setActivityId(e.target.value)} placeholder="Catalog/program/activity ID" /></Field><Field label="Activity title"><input className="form-field" value={activityTitle} onChange={(e) => setActivityTitle(e.target.value)} /></Field><Field label="Activity date"><input type="datetime-local" className="form-field" value={activityDate} onChange={(e) => setActivityDate(e.target.value)} /></Field><Field label="Deadline"><input type="datetime-local" className="form-field" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></Field><Field label="Location"><input className="form-field" value={location} onChange={(e) => setLocation(e.target.value)} /></Field><Field label="Description" wide><textarea className="form-field min-h-24" value={description} onChange={(e) => setDescription(e.target.value)} /></Field>
    </div><div className="mt-5 space-y-3">{questions.map((question, index) => <div key={question.id} className="grid gap-2 border border-ink/10 p-3 sm:grid-cols-[2rem_1fr_12rem_auto]"><span className="pt-3 text-sm font-bold">{index + 1}</span><input className="form-field" value={question.title} onChange={(e) => updateQuestion(question.id, { title: e.target.value })} placeholder="Question" /><select className="form-field" value={question.type} onChange={(e) => updateQuestion(question.id, { type: e.target.value as GoogleQuestionType })}>{questionTypes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><div className="flex gap-1"><button aria-label="Move question up" disabled={index === 0} onClick={() => moveQuestion(index, -1)} className="h-11 w-9 border border-ink/15 disabled:opacity-30"><ArrowUp className="mx-auto h-4 w-4" /></button><button aria-label="Move question down" disabled={index === questions.length - 1} onClick={() => moveQuestion(index, 1)} className="h-11 w-9 border border-ink/15 disabled:opacity-30"><ArrowDown className="mx-auto h-4 w-4" /></button><button aria-label="Delete question" onClick={() => setQuestions((current) => current.filter((item) => item.id !== question.id))} className="h-11 w-9 border border-red-900/20 text-red-700"><Trash2 className="mx-auto h-4 w-4" /></button></div><label className="col-start-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={question.required} onChange={(e) => updateQuestion(question.id, { required: e.target.checked })} />Required</label>{["multiple_choice", "checkbox", "dropdown"].includes(question.type) ? <input className="form-field sm:col-span-2" value={question.options.join("\n")} onChange={(e) => updateQuestion(question.id, { options: e.target.value.split("\n") })} placeholder="One choice per line" /> : null}</div>)}</div>
    <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setQuestions((current) => [...current, blankQuestion()])} className="inline-flex min-h-10 items-center gap-2 border border-ink/20 px-4 text-sm font-semibold"><Plus className="h-4 w-4" />Question</button><button disabled={busy || !data.connection.connected || !title.trim()} onClick={() => void create()} className="min-h-10 bg-ink px-5 text-sm font-semibold text-paper disabled:opacity-45">{busy ? "Working…" : "Create actual Google Form"}</button></div></div> : null}
    <div className="mt-8 grid gap-4">{forms.map((form) => <article key={form.id} className="border border-ink/12 bg-white/60 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-brass">{form.status} · Source: Google Forms</p><h2 className="mt-1 text-xl font-bold text-ink">{form.title}</h2><p className="mt-2 text-sm text-ink/60">Responses {form.response_count} · Last sync {form.last_response_sync_at ? new Date(form.last_response_sync_at).toLocaleString() : "never"}</p></div><div className="flex flex-wrap gap-2"><a href={form.responder_url} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-10 items-center gap-2 border border-ink/20 px-3 text-sm font-semibold">Apply form <ExternalLink className="h-4 w-4" /></a>{form.edit_url ? <a href={form.edit_url} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-10 items-center gap-2 border border-ink/20 px-3 text-sm font-semibold">Edit in Google <ExternalLink className="h-4 w-4" /></a> : null}</div></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void responses(form, true)} className="inline-flex min-h-10 items-center gap-2 bg-navy px-4 text-sm font-semibold text-paper"><RefreshCw className="h-4 w-4" />Sync responses</button><button onClick={() => void responses(form)} className="min-h-10 border border-ink/20 px-4 text-sm font-semibold">View mirror</button>{!initialAccess.isReadOnly && form.status === "open" ? <button onClick={() => void status(form, "closed")} className="min-h-10 border border-ink/20 px-4 text-sm font-semibold">Close</button> : null}{!initialAccess.isReadOnly && form.status === "closed" ? <button onClick={() => void status(form, "open")} className="min-h-10 border border-ink/20 px-4 text-sm font-semibold">Reopen</button> : null}{!initialAccess.isReadOnly && form.status !== "archived" ? <button onClick={() => void status(form, "archived")} className="min-h-10 border border-red-900/20 px-4 text-sm font-semibold text-red-700">Archive</button> : null}</div></article>)}{!forms.length ? <p className="border border-dashed border-ink/20 p-8 text-center text-sm text-ink/55">No Google Form is registered for this club.</p> : null}</div>
    {selected && mirror ? <div className="fixed inset-0 z-50 overflow-y-auto bg-ink/55 p-4"><div className="mx-auto max-w-5xl bg-paper p-5 sm:p-7"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase text-brass">Read-only mirror</p><h2 className="font-serif text-3xl font-semibold">Google Form responses</h2></div><button onClick={() => { setSelected(null); setMirror(null); }} aria-label="Close"><X className="h-6 w-6" /></button></div><div className="mt-5 grid gap-3">{mirror.responses.map((response) => <article key={response.id} className="border border-ink/10 bg-white/60 p-4"><p className="text-xs font-semibold text-ink/55">{new Date(response.submitted_at).toLocaleString()} · {response.respondent_email || "Email unavailable"}</p><dl className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(response.answers_json).map(([question, answers]) => <div key={question}><dt className="text-xs font-bold text-ink/55">{question}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{answers.join(", ") || "-"}</dd></div>)}</dl></article>)}{!mirror.responses.length ? <p className="py-8 text-center text-sm text-ink/55">No synchronized responses.</p> : null}</div></div></div> : null}
  </div></section>;
}

function Field({ children, label, wide = false }: { children: React.ReactNode; label: string; wide?: boolean }) { return <label className={`grid gap-1 text-sm font-semibold ${wide ? "sm:col-span-2 lg:col-span-3" : ""}`}><span>{label}</span>{children}</label>; }
