"use client";

import { ChevronLeft, ChevronRight, LoaderCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { TraditionalLiquorAnalyticsFilters, TraditionalLiquorMetricPeriod, TraditionalLiquorMetricType, TraditionalLiquorPagedResult, TraditionalLiquorSalesRow } from "@/lib/traditional-liquor/types";

const metricLabels: Record<TraditionalLiquorMetricType, string> = { SOURCE_PURCHASE_COUNT: "구매수", KEEP_COUNT: "찜/보관수", REVIEW_COUNT: "리뷰수", WISH_COUNT: "위시수", SEARCH_RANK: "검색 순위", GIFT_RANK: "선물 순위", CATEGORY_RANK: "카테고리 순위" };
const allMetrics = Object.keys(metricLabels) as TraditionalLiquorMetricType[];
const periods: Array<{ value: TraditionalLiquorMetricPeriod; label: string }> = [{ value: "LATEST", label: "최신" }, { value: "7D", label: "7일 증가량" }, { value: "30D", label: "30일 증가량" }, { value: "HISTORY", label: "전체 추이" }];

export function TraditionalLiquorSalesAnalytics({ initialFilters, mode = "page", query, syncUrl }: { initialFilters?: TraditionalLiquorAnalyticsFilters; mode?: "page" | "embedded"; query: string; syncUrl: (values: Record<string, string>) => void }) {
  const [ready, setReady] = useState(mode === "embedded");
  const [platform, setPlatform] = useState(initialFilters?.platformCode ?? "NAVER"); const [metric, setMetric] = useState<TraditionalLiquorMetricType>(initialFilters?.metricType ?? "SOURCE_PURCHASE_COUNT");
  const [period, setPeriod] = useState<TraditionalLiquorMetricPeriod>(initialFilters?.period ?? "LATEST"); const [page, setPage] = useState(1);
  const [data, setData] = useState<TraditionalLiquorPagedResult<TraditionalLiquorSalesRow> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [retry, setRetry] = useState(0);
  useEffect(() => { if (mode === "embedded") return; const params = new URLSearchParams(window.location.search); setPlatform(params.get("platform") || "NAVER"); setMetric((params.get("metric") as TraditionalLiquorMetricType) || "SOURCE_PURCHASE_COUNT"); setPeriod((params.get("period") as TraditionalLiquorMetricPeriod) || "LATEST"); setPage(Math.max(1, Number(params.get("page")) || 1)); setReady(true); }, [mode]);
  useEffect(() => {
    if (!ready) return;
    const controller = new AbortController(); setLoading(true); setError("");
    const params = new URLSearchParams({ q: query, platform, metric, period, page: String(page) });
    fetch(`/api/v4/traditional-liquor/analytics/sales?${params}`, { cache: "no-store", signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); return body.results; }).then(setData).catch((reason) => { if (reason.name !== "AbortError") setError(reason instanceof Error ? reason.message : "시장 지표를 불러오지 못했습니다."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    syncUrl({ platform, metric, period, page: String(page) }); return () => controller.abort();
  }, [metric, page, period, platform, query, ready, retry, syncUrl]);
  const isPopularity = platform === "KAKAO_GIFT" || metric !== "SOURCE_PURCHASE_COUNT";
  const availableMetrics = useMemo(() => platform === "KAKAO_GIFT" ? allMetrics.filter((item) => ["WISH_COUNT", "REVIEW_COUNT", "GIFT_RANK", "CATEGORY_RANK"].includes(item)) : allMetrics, [platform]);
  const availability = data?.availability;
  const periodAvailable = period === "LATEST" ? availability?.latest : period === "7D" ? availability?.sevenDays : period === "30D" ? availability?.thirtyDays : availability?.history;
  function changePlatform(value: string) { setPlatform(value); setPage(1); const next = value === "KAKAO_GIFT" ? "WISH_COUNT" : "SOURCE_PURCHASE_COUNT"; setMetric(next); }
  return <section className="border border-white/10 bg-white/[0.035] p-4 md:p-5">
    <div className="mb-4 border-l-2 border-[#f7c76b] bg-black/20 px-4 py-3"><p className="text-sm font-bold text-white">{isPopularity ? "인기도 지표" : "판매량 지표"}</p><p className="mt-1 text-xs leading-5 text-white/48">{isPopularity ? "위시·리뷰·순위는 인기도 지표이며 실제 판매량으로 해석하지 않습니다." : "SOURCE_PURCHASE_COUNT의 최신 누적값과 기간 증가량을 표시합니다."}</p></div>
    <div className="grid gap-3 md:grid-cols-2"><Filter label="플랫폼"><select value={platform} onChange={(event) => changePlatform(event.target.value)} className={controlClass}>{data?.platforms.map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></Filter><Filter label="지표"><select value={metric} onChange={(event) => { setMetric(event.target.value as TraditionalLiquorMetricType); setPage(1); }} className={controlClass}>{availableMetrics.map((item) => <option key={item} value={item}>{metricLabels[item]}</option>)}</select></Filter></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{periods.map((item) => { const available = item.value === "LATEST" ? availability?.latest : item.value === "7D" ? availability?.sevenDays : item.value === "30D" ? availability?.thirtyDays : availability?.history; return <button key={item.value} type="button" onClick={() => { setPeriod(item.value); setPage(1); }} className={`min-h-14 border px-3 text-left text-xs font-bold transition ${period === item.value ? "border-[#f7c76b] bg-[#f7c76b] text-[#17191a]" : "border-white/15 text-white/65 hover:border-white/35"}`}><span className="block">{item.label}</span><span className={`mt-1 block text-[10px] ${period === item.value ? "text-[#17191a]/65" : available ? "text-emerald-300" : "text-white/30"}`}>{available ? "사용 가능" : "데이터 부족"}</span></button>; })}</div>
    {loading ? <Message><LoaderCircle className="h-5 w-5 animate-spin" />전통주 데이터를 불러오는 중...</Message> : error ? <Message>전통주 데이터를 불러오지 못했습니다.<button type="button" onClick={() => setRetry((current) => current + 1)} className="border border-[#f7c76b]/45 px-3 py-2 text-xs font-bold text-[#f7c76b]">다시 시도</button></Message> : data?.rows.length ? <>{periodAvailable === false ? <div className="mt-5 border border-[#f7c76b]/25 bg-[#f7c76b]/5 px-4 py-3 text-sm text-white/58">비교 가능한 이전 데이터가 없습니다. Snapshot이 누적되면 자동으로 활성화됩니다.</div> : null}<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-y border-white/10 text-white/40"><tr><th className="px-3 py-3">순위</th><th className="px-3 py-3">상품</th><th className="px-3 py-3">플랫폼</th><th className="px-3 py-3">업체</th><th className="px-3 py-3">{period === "LATEST" ? metricLabels[metric] : periods.find((item) => item.value === period)?.label}</th><th className="px-3 py-3">기준 Snapshot</th><th className="px-3 py-3">최신 Snapshot</th></tr></thead><tbody>{data.rows.map((row, index) => <tr key={`${row.metricScope}:${row.sourceEntityId}`} className="border-b border-white/8"><td className="px-3 py-3 text-white/40">{(data.page - 1) * data.limit + index + 1}</td><td className="px-3 py-3 font-semibold text-white/85">{row.productName}</td><td className="px-3 py-3 text-white/60">{row.platformName}</td><td className="px-3 py-3 text-white/50">{row.sellerName}</td><td className="px-3 py-3 font-bold text-[#f7c76b]">{formatMetricResult(row, period)}</td><td className="px-3 py-3 text-white/38">{row.baselineObservedAt ? date(row.baselineObservedAt) : "-"}</td><td className="px-3 py-3 text-white/38">{date(row.latestObservedAt)}</td></tr>)}</tbody></table></div>{period === "HISTORY" && data.rows.some((row) => row.history.length >= 2) ? <TrendDetails rows={data.rows} /> : null}<Pagination page={data.page} totalPages={data.totalPages} total={data.total} setPage={setPage} /></> : <Message>선택한 조건의 Production metric snapshot이 없습니다.</Message>}
  </section>;
}
const controlClass = "h-10 w-full border border-white/15 bg-[#0e1112] px-3 text-sm text-white outline-none focus:border-[#f7c76b]";
function Filter({ children, label }: { children: React.ReactNode; label: string }) { return <label><span className="mb-2 block text-[10px] font-bold tracking-[0.12em] text-white/42">{label}</span>{children}</label>; }
function Message({ children }: { children: React.ReactNode }) { return <div className="mt-5 flex min-h-40 flex-col items-center justify-center gap-3 border border-white/10 text-center text-sm text-white/50">{children}</div>; }
function Pagination({ page, setPage, total, totalPages }: { page: number; setPage: (value: number) => void; total: number; totalPages: number }) { return <div className="mt-4 flex items-center justify-between text-xs text-white/45"><span>총 {total.toLocaleString("ko-KR")}개</span><div className="flex items-center gap-3"><button type="button" disabled={page <= 1} onClick={() => setPage(page - 1)} className="border border-white/15 p-2 disabled:opacity-25"><ChevronLeft className="h-4 w-4" /></button><span>{page} / {totalPages}</span><button type="button" disabled={page >= totalPages} onClick={() => setPage(page + 1)} className="border border-white/15 p-2 disabled:opacity-25"><ChevronRight className="h-4 w-4" /></button></div></div>; }
function date(value: string) { return new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function formatMetricResult(row: TraditionalLiquorSalesRow, period: TraditionalLiquorMetricPeriod) { if (period === "LATEST") return row.latestValue.toLocaleString("ko-KR"); if (row.dataStatus !== "AVAILABLE" || row.deltaValue === null) return "데이터 부족"; if (period === "HISTORY") return `${row.baselineValue?.toLocaleString("ko-KR")} → ${row.latestValue.toLocaleString("ko-KR")}`; return `${row.deltaValue >= 0 ? "+" : ""}${row.deltaValue.toLocaleString("ko-KR")}${row.deltaPercent === null ? "" : ` (${row.deltaPercent >= 0 ? "+" : ""}${row.deltaPercent}%)`}`; }
function TrendDetails({ rows }: { rows: TraditionalLiquorSalesRow[] }) { return <div className="mt-5 space-y-3">{rows.filter((row) => row.history.length >= 2).map((row) => <details key={`trend:${row.metricScope}:${row.sourceEntityId}`} className="border border-white/10 bg-black/15"><summary className="cursor-pointer px-4 py-3 text-sm font-semibold text-white/75">{row.productName} · {row.history.length} snapshots</summary><div className="overflow-x-auto border-t border-white/10"><table className="w-full min-w-[540px] text-left text-xs"><thead className="text-white/35"><tr><th className="px-4 py-2">날짜</th><th className="px-4 py-2">누적값</th><th className="px-4 py-2">이전 대비</th></tr></thead><tbody>{row.history.map((point) => <tr key={point.observedAt} className="border-t border-white/8"><td className="px-4 py-2 text-white/50">{date(point.observedAt)}</td><td className="px-4 py-2 text-white/75">{point.value.toLocaleString("ko-KR")}</td><td className="px-4 py-2 text-[#f7c76b]">{point.deltaFromPrevious === null ? "-" : `${point.deltaFromPrevious >= 0 ? "+" : ""}${point.deltaFromPrevious.toLocaleString("ko-KR")}`}</td></tr>)}</tbody></table></div></details>)}</div>; }
